version: "3.4"

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: XXX
    predictor:
        image: predictor
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
            - DEBUG=TRUE
        volumes:
            - .:/app
        command: python run.py
